export const ENV = {
  SHEET_ID: process.env.GOOGLE_SHEETS_SPREADSHEET_ID!,
  SA_KEY: process.env.GOOGLE_SERVICE_ACCOUNT_KEY!,
  SHEET_ENTRIES: process.env.GOOGLE_SHEETS_ENTRIES_SHEET || 'entries',
  SHEET_PAIRINGS: process.env.GOOGLE_SHEETS_PAIRINGS_SHEET || 'pairings',
  SHEET_LEADERBOARD: process.env.GOOGLE_SHEETS_LEADERBOARD_SHEET || 'leaderboard',
  SHEET_RESULTS: process.env.GOOGLE_SHEETS_RESULTS_SHEET || 'results',
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  SUPABASE_ANON: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  SUPABASE_SERVICE: process.env.SUPABASE_SERVICE_ROLE_KEY!,
  SUPABASE_BUCKET: process.env.SUPABASE_BUCKET || 'gallery',
  ENABLE_GALLERY_UPLOAD: (process.env.NEXT_PUBLIC_ENABLE_GALLERY_UPLOAD || '0') === '1',
  ENABLE_GALLERY_MANAGE: (process.env.NEXT_PUBLIC_ENABLE_GALLERY_MANAGE || '0') === '1',
};
